### ISSUE TITLE
Question regarding release and how to get the. zip

### ISSUE THREAD

**Issue by ShounenArgha** [Magisk-Modules-Alt-Repo/YAKT#1]
Am a new guy at this root tasks and i want to use the module here.but i can't understand whether i should just clone the repo (dl .zip)thing or there isn't any release yet.

Dev, @NotZeetaa awaiting ur reply

**Comment by NotZeetaa** [comment]
U can use Fox2Code magisk manager to install this modules or join the support link
Fox2Code: https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.4.4
Support: https://t.me/ZeetaaTweaks
